### ISSUE TITLE
Where your implementation is a success, but mine failed

### ISSUE THREAD

**Issue by mytech-today-now** [presenta-software/presenta-lib#13]
I was thinking of my software more as an app/website, rather than a player for an existing format (markdown) with extra features.

Using markdown, a common format, as the human readable-writable format is just brilliant.  It probably seems obvious to you, but it just flew over my head completely.  It makes all the difference in terms of usability, # of potential existing users who already know markdown, and making the files manageable from a user perspective.

**Comment by mytech-today-now** [comment]
I have material that I can send to you if you want to collaborate beyond me posting here.  lmk

**Comment by abusedmedia** [comment]
Credits where's due. The concept of converting markdown to slides is not mine and there are many examples out there.
You can have a glimpse here: https://gist.github.com/johnloy/27dd124ad40e210e91c70dd1c24ac8c8

PRESENTA wants to go a little bit further, though, since the core of the project is a generic data structure, markdown is just a flavuor.

I'd be happy to see some materials from you. 
You can reach me on hello@fabiofranchino.com
