### ISSUE TITLE
Viewer tracking - Google Analytics?

### ISSUE THREAD

**Issue by mytech-today-now** [presenta-software/presenta-lib#17]
https://play.presenta.cc/view/kLRsm375w7i7j

How do I add Google Analytics to a presenta?

I tried adding, but it didn't work, see presenta above.

    ```javascript
    <script type="text/javascript">(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0], j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);}(window,document,'script','dataLayer','GTM-MF3JGRJ');</script>
    ```

The javascript is visible in the presentation, or maybe that's expected behavior?

**Comment by abusedmedia** [comment]
Hi @mytech-today-now 

You cannot inject `script` within markdown for security reasons.

The solution is to use a plugin for that specific functionality.
I've already thought about an official Presenta plugin to integrate G-Analytics.
Since I didn't need it I've never created it.

If it's something useful, I can consider to create it. 

Wondering if it's just enough to track the presentation access or also the single slides viewed by users.
Thought?
