### ISSUE TITLE
Not understanding how to create block with Text and Youtube video - My attempt breaks the software

### ISSUE THREAD

**Issue by mytech-today-now** [presenta-software/presenta-lib#18]
I created a presenta in a manner I thought would work, but it is not producing the expected results.

[Text mixed with YT video incorrect (2).txt](https://github.com/presenta-software/presenta-lib/files/6017253/Text.mixed.with.YT.video.incorrect.2.txt)
Text mixed with YT video incorrect - https://play.presenta.cc/view/MudloeR5RhKms

**Comment by mytech-today-now** [comment]
Figured it out:  All Text lines must be prepended with ###. no exceptions.

Status: Closed

**Comment by abusedmedia** [comment]
I think you've found an edge case bug.
I'll investigate on it.
Thanks!

**Comment by abusedmedia** [comment]
It was an issue related to the different carriage return encoding that probably was brought with the copy/paste with your text editor, more details [here](https://developer.mozilla.org/en-US/docs/Glossary/CRLF) if you are curious.

Now Playground should work as expected.
To see the effect, since it's a PWA, go to the tool and wait until you see the updated message (it needs to download the new version of the tool in background).

FYI: your previous shared document is still broken in the exported version, but if you edit it, you can see the difference.
