### ISSUE TITLE
inconsistent download/fork/share features

### ISSUE THREAD

**Issue by mytech-today-now** [presenta-software/presenta-lib#21]
Perhaps I'm not doing it right:

When I fork, then share a presenta, I am left at the new presenta shared screen.

I can copy the link, then open the newly "created" presenta by clicking on the "open in editor link".

If I add new content to the opened presenta, it is not ever saved.  If I view my presenta, my new changes are present, but when I "esc" back to the editor the changes are lost, and it's back to the original newly "created" presenta that I "opened in the editor".

It seems like the new content will only save when I fork the presenta, but then it's not clear to the user what exactly just happened when I clicked fork, because I can still edit and the only visual indicator of any change is that now it says share.

Maybe, you might want to have the "naming process" of the fork/share occur when the presenta gets forked, so that it's clear to the user that they are working on a newly "named" fork, which can then be shared.

I don't know, there is something that doesn't work in the flow I how to fork/share, and at what point I can download the forked version.

**Comment by abusedmedia** [comment]
I understand that the current situation is not seamless (if compared with the usual tools where you can save many/manage documents) because you can have only **one** document saved locally while you can explore shared documents at the same time.

So, there are two type of edit mode:
- edit your locally saved document, on each type the document is updated locally and automatically
- edit any shared document, without overwriting your current one, so you can type but nothing is saved

Now, to mitigate a bit, I've added a message when you start editing a shared document, reminding you that all these edits are ephemeral, with the only purpose to explore/learn.
If you want to keep those edits, then you've been asked to **fork** it explicitly.

It's not perfect, I know, but to have a solid experience the tool should be heavily redesigned incorporating more functonalities to accomodate multi-document management.

I'm not planning to make such changes on Playground, but I'm considering to create a different tool that might have account capability as well as multi-document management and many more features.

Let's see.
